# Generated by Django 3.2.6 on 2021-08-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210810_2311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
